//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "attendance_period")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub created_by: Option<Uuid>,
    pub updated_by: Option<Uuid>,
    pub start_at: DateTimeWithTimeZone,
    pub end_at: DateTimeWithTimeZone,
    pub processed: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::employee_attendance::Entity")]
    EmployeeAttendance,
    #[sea_orm(has_many = "super::employee_overtime::Entity")]
    EmployeeOvertime,
    #[sea_orm(has_many = "super::employee_reimbursement::Entity")]
    EmployeeReimbursement,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedBy",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User2,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UpdatedBy",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User1,
}

impl Related<super::employee_attendance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmployeeAttendance.def()
    }
}

impl Related<super::employee_overtime::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmployeeOvertime.def()
    }
}

impl Related<super::employee_reimbursement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmployeeReimbursement.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
